### ISSUE TITLE
建议原语言添加detect language，非常有用

### ISSUE THREAD

**Issue by liushawulan** [wizyoung/googletranslate.popclipext#10]
这样就不用每次去设置了，经常需要用到不同的原语言，目标语言可以自己改。比如德语、法语等的原语言，可以自动检测语言，输出一种目标语言，谢谢哈。非常棒的插件。，

**Comment by wizyoung** [comment]
`自动检测语言，输出一种目标语言`，现在不就是这样设定的吗

**Comment by liushawulan** [comment]
:) 现在source language里面没有自动检测语言 的选项，只能选择一种语言，我选了法语，目标语言是英语，这样我复制一句中文或德语，插件就不工作了：）

**Comment by wizyoung** [comment]
你是安装的最新的版本吗，我这里没有问题

**Comment by liushawulan** [comment]
谢谢：） 我刚才发现，是我设置了英语和法语作为原语言、输出语言，我现在都改成英语，就无论什么原语言，都输出英语了，非常棒。谢谢。
