### ISSUE TITLE
Hope the top-right bubble effect back

### ISSUE THREAD

**Issue by bernardyeszero** [wizyoung/googletranslate.popclipext#11]
Dear developer,

Thanks for this plug-in. I think the top-right bubble is quite better for me because I don't need to click the OK or Copy button. I would be pleased to see the top-right effect comes back.

**Comment by wizyoung** [comment]
You can just press "Enter" to close the pop-up window. Since I'm very busy these days, may I'll release a special version with top-right bubble effect weeks later when I'm free.

**Comment by bernardyeszero** [comment]
Thanks!

**Comment by wizyoung** [comment]
I still think the current display manner is better than the top-right pop window. However, I made a special edition with the old display effect for you. Sorry for the late reply.
Download link: https://www.lanzous.com/i83ueje

**Comment by bernardyeszero** [comment]
Thanks for this special version! I appreciate it!
