### ISSUE TITLE
翻译结果不是谷歌翻译

### ISSUE THREAD

**Issue by jilex** [wizyoung/googletranslate.popclipext#12]
近期发现翻译结果的可读性下降，后来发现结果与谷歌翻译不一致，请问还会更新吗？

**Comment by wizyoung** [comment]
谢谢反馈，这个是 py-googletrans 的问题 (https://github.com/ssut/py-googletrans/issues/138)

最近手头事情比较多，暂时观望一下看原作者是否更新，不行的话可能我自己去着手解决

**Comment by wizyoung** [comment]
修复了
