### ISSUE TITLE
双屏的时候，在附屏上点选翻译，好像翻译结果只能在主屏显示？

### ISSUE THREAD

**Issue by lwjcjmx123** [wizyoung/googletranslate.popclipext#13]
能优化到附屏显示吗

**Comment by lwjcjmx123** [comment]
哦，是在附屏浏览器是全屏显示的时候，如果非全屏显示也能在当前屏幕显示翻译结果

**Comment by wizyoung** [comment]
这个是 popclip 设定的，并不是本插件的设定。所以无法改变。可以去 https://github.com/pilotmoon/PopClip-Extensions 反馈一下这个问题。
