### ISSUE TITLE
近期似乎失效，无法正常使用

### ISSUE THREAD

**Issue by jjaychen1e** [wizyoung/googletranslate.popclipext#14]
不知道是不是个例，最近（可能一两个月？）无法正常使用。之前一直是点击后一直处于 pending 状态，现在是点击后直接没有反应。尝试过重新安装、重新赋予权限，是一样的表现。

macOS 11.0.1 (20B29)

**Comment by wizyoung** [comment]
感谢反馈，应该是 google 的 token 机制发生了变动，本周末我修复一下

**Comment by wizyoung** [comment]
已修复
