### ISSUE TITLE
Popclip更新2021.11版本后插件失效

### ISSUE THREAD

**Issue by c14h19no2** [wizyoung/googletranslate.popclipext#16]
版本号2021.11 (1003785)，popclip从AppStore更新后显示googletranslate (v3.0)不兼容，重装v3.0后仍然失败，显示`Cannot Install Extension，No such executable in PATH: (null)`

**Comment by wizyoung** [comment]
可能是客户端更改了一些加载机制, 我研究下, 尽快 fix

**Comment by c14h19no2** [comment]
感谢！

**Comment by wizyoung** [comment]
v3.1 已修复
