### ISSUE TITLE
翻译弹出窗口不显示

### ISSUE THREAD

**Issue by lonelygo** [wizyoung/googletranslate.popclipext#2]
Hi，版本信息：OS 10.13.2 PopClip 1.5.8

选中点翻译后，弹出 黑色 小窗口，进度旋转结束后，无弹出翻译结果窗口。

**Comment by molvqingtai** [comment]
同问，弹窗窗口不显示
macOS 10.13 
PopClip 1.6

**Comment by wizyoung** [comment]
@lonelygo @molvqingtai 
感觉多半是网络问题造成，可以尝试以下操作：
网页打开translate.google.cn(com)确保网络能正常访问后再尝试使用插件。

@molvqingtai 另外, PopClip 1.6 已释出了吗？官网最新测试版显示仍为1.5.8.1

**Comment by lonelygo** [comment]
@wizyoung 之前邮件也沟通过，网页是能正常打开 translate.google.cn/com 的，但是弹出窗口还是出不来，我觉得这个锅有可能是macOS 的。
因为之前用的另一个基于Microsoft 的api的插件，也不能弹出翻译了，只能弹出黑框中间一个X。

**Comment by wizyoung** [comment]
@lonelygo 不知道是不是macOS的问题。这个月比较忙，下个月初我仔细研究一下

**Comment by tshu-w** [comment]
~~同样的问题~~
macOS 10.13.2
popclip 1.5.8

-----

然后发现重新安装就好了_(:з」∠)_，之前是重装系统直接用 dotfile 恢复 popclip 配置出现的问题。

**Comment by wizyoung** [comment]
@lonelygo @molvqingtai @Voleking 请尝试最新的版本，看问题是否解决。

**Comment by molvqingtai** [comment]
@wizyoung 
完美运行
MAC OS 10.13.2
popclip 1.5.8

**Comment by molvqingtai** [comment]
@wizyoung 
完美运行
MAC OS 10.13.2
popclip 1.5.8

**Comment by lonelygo** [comment]
用各种梯子的话，发现居然不弹窗和代理有关。
开启代理，不弹窗的话，手动加上FTP的代理地址再试试看。

**Comment by qazhuhuihao** [comment]
同样的问题
MAC OS 10.13.6
popclip 1.5.8

关代理 重装插件 重装popclip,重启,都没用

**Comment by wizyoung** [comment]
@qazhuhuihao google translate 的 token 变了，马上更新

**Comment by tortoo** [comment]
更新以后终于可以了！一直在用的好插件，感谢作者！

**Comment by qazhuhuihao** [comment]
原来已经更新了!非常好用的插件,感谢作者!

**Comment by iowronn** [comment]
> @qazhuhuihao google translate 的 token 变了，马上更新

token又更新了吗？今天发现翻译窗口无响应。

**Comment by wizyoung** [comment]
@Nenznay 是的，等待 py-googletrans 维护吧

**Comment by wizyoung** [comment]
@Nenznay 已修复，请下载最新版

**Comment by qazhuhuihao** [comment]
赞

**Comment by jjaychen1e** [comment]
> @Nenznay 已修复，请下载最新版

感谢

**Comment by wizyoung** [comment]
新版已发布，中心弹窗显示时间不再受限制，同时加入了自动更新提醒。

**Comment by toure00** [comment]
我这里用不成啊，小菊花转完，啥也没弹出来，
https://translate.google.cn   （正常打开）
https://translate.google.com  (代理打开)
PopClip 版本：2019.9.1
插件最新版

![2019-10-18 21 00 24](https://user-images.githubusercontent.com/33457469/67098766-578f5600-f1ef-11e9-8563-884c61549ee5.gif)
