### ISSUE TITLE
可以参考这个把翻译内容显示在鼠标周围

### ISSUE THREAD

**Issue by qq12157138** [wizyoung/googletranslate.popclipext#3]
https://github.com/harmy/PopClip-Extensions

**Comment by wizyoung** [comment]
@qq12157138 其实我第一次就尝试使用的是这种显示方式，但是这种方式下不支持换行显示，翻译结果太长时，屏幕显示不下，就放弃了

**Comment by qq12157138** [comment]
@wizyoung 其实现在就算在右上角也有个尴尬的问题，虽然有选项把每次翻译结果都复制到剪切板，显然这样不够友好。如果能点击右上角的弹窗再复制到剪切板就很好了。

**Comment by wizyoung** [comment]
@qq12157138 试试显示在正中间吧，我自己就用这种模式，感觉很方便

**Comment by qq12157138** [comment]
@wizyoung 显示在中间这个是很好，如果这个窗体是你设置的，我觉得你可以把ok给去掉，因为非让选一个按钮才能取消也是不太友好。可以丢失焦点自动关闭。

**Comment by wizyoung** [comment]
@qq12157138 个人觉得有OK按钮的形式更好。
