### ISSUE TITLE
请问center弹窗的时间可以手动调整吗？

### ISSUE THREAD

**Issue by aitsc** [wizyoung/googletranslate.popclipext#5]
或者随着内容的变长，显示时间自动变长？
我总是遇到还没读完内容弹窗就消失了。

**Comment by tshu-w** [comment]
可以把鼠标移过去？

**Comment by aitsc** [comment]
是中央弹窗，不是通知条形式。

**Comment by tshu-w** [comment]
@burongjiashe 抱歉没注意看🤣

**Comment by wizyoung** [comment]
@burongjiashe 受所用的 cocoaDialog 限制，center 弹窗不能调整时间。后续会换 GUI 框架，请留意后续更新。

**Comment by aitsc** [comment]
好的，谢谢了。

**Comment by wizyoung** [comment]
@burongjiashe 新版已发布，目前只保留了中间弹窗的形式，去除了自动消失的时间限制。

**Comment by aitsc** [comment]
我安装后中间弹窗好像还是会在30秒后自动消失？

**Comment by wizyoung** [comment]
@burongjiashe 好像是 PopClip 的限制，我排查下

**Comment by wizyoung** [comment]
@burongjiashe 确认了是 PopClip 的问题，Long Running 最大显示时间 30 s

**Comment by aitsc** [comment]
之前的中央弹窗好像也是30秒。那还有绕开的方法吗？

**Comment by wizyoung** [comment]
@burongjiashe 我尝试一下

**Comment by aitsc** [comment]
翻译带括号的句子好像无法发音。

**Comment by wizyoung** [comment]
@burongjiashe 发音这个是 macOS 的限制。算了，打算撤回上一个版本，PopClip 受限制太多，debug 也很麻烦，下次有时间写一个 Alfred 的 workflow，比如双击 cmd 进行翻译，PopClip不折腾了。

**Comment by wizyoung** [comment]
@burongjiashe @Voleking 新版本解决中心弹窗自动消失的问题了
