### ISSUE TITLE
请问能不能更改或者自定义字体的大小？

### ISSUE THREAD

**Issue by bootcamp6** [wizyoung/googletranslate.popclipext#6]
弹窗的字太小了，mac分辨率高了就看不清

**Comment by jjaychen1e** [comment]
能否让中心弹窗不会自动消失？有时候可能需要一直放在边上，手动关闭。有时候文字太长还没看完就已经消失了。（Top right可以把鼠标放在上面不自动消失，Center好像不行）

**Comment by wizyoung** [comment]
@JJAYCHENooo 请等待更新
@bootcamp6 这个没法调，是系统自动调的。近期更新后可能字体会稍微大一点

**Comment by wizyoung** [comment]
@bootcamp6 @JJAYCHENooo 已更新
