### ISSUE TITLE
更新后的一个小问题

### ISSUE THREAD

**Issue by jjaychen1e** [wizyoung/googletranslate.popclipext#7]
非常感谢更新，新版更新后弹窗已经不会自动消失。但是出现一个新的问题，在窗口关闭前 PopClip 会被占用导致无法继续使用 PopClip。不知道能否修正这一点，如果可以修正的话应该就可以同时借此做到同时放置多个弹窗。

**Comment by wizyoung** [comment]
是这样的，popclip 默认不允许插件运行时间超过 30 秒，与作者沟通后采取的方案是强制让 popclip 等待插件运行结束，在这期间 popclip 不可执行其他任务，也就是你说的情况。
其实之前我也试过单独开一个后台进程，不受 popclip 控制，popclip 只负责调度这个进程，这样 popclip 无法接受插件返回值，比如复制功能等都不能实现了。
权衡之后，我选择了前一个方案。这是 popclip 局限性导致的。
