### ISSUE TITLE
显示翻译结果的交互设计讨论

### ISSUE THREAD

**Issue by Wei-Xia** [wizyoung/googletranslate.popclipext#8]
非常感谢开发这款翻译插件！

目前选中后翻译是弹框式，可以选择 copy 或 OK 来使之消失。

请问开发者有考虑过选择悬浮框来呈现结果吗？如下图所示。

![image](https://user-images.githubusercontent.com/9309906/50231459-da9c1180-037c-11e9-86b4-cde1121f8e10.png)

所以得看「复制」翻译结果的需求是否强烈，毕竟可以减少用户额外的一步操作。

**Comment by wizyoung** [comment]
@Wei-Xia 感谢反馈，你图中显示的悬浮窗是 popclip 自带的显示模式，我最早尝试过，它不支持长文本换行，因此不适合于显示大段的翻译结果。我个人以及身边的朋友都偏好于弹窗显示，不自动消失也是为了在长文本翻译结果情况下，可以自由决定查看结果的时间。当然，你不想点击按钮的话，可以直接按下回车让悬浮窗消失。复制翻译结果的需求网友反映很强烈，所以我才加的，因此不考虑移除这个按钮了。

**Comment by Wei-Xia** [comment]
@wizyoung 谢谢你的回复，看来这个是强需求！哈哈！
